---
image: kopkop/kibana

elasticsearchHosts: "https://elasticsearch-master-headless:9200"

protocol: http

extraEnvs:
  - name: 'ELASTICSEARCH_USERNAME'
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: username
  - name: 'ELASTICSEARCH_PASSWORD'
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password
  - name: 'KIBANA_ENCRYPTION_KEY'
    valueFrom:
      secretKeyRef:
        name: kibana
        key: encryptionkey

kibanaConfig:
  kibana.yml: |
    xpack.security.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
    elasticsearch.ssl:
      certificateAuthorities: /usr/share/kibana/config/certs/elastic-certificate.pem
      verificationMode: certificate

secretMounts:
  - name: elastic-certificate-pem
    secretName: elastic-certificate-pem
    path: /usr/share/kibana/config/certs

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx

  enabled: true
  hosts:
  - kibana.uno.sh
  tls:
  - hosts:
    - kibana.uno.sh
    secretName: kibana.uno.sh-prod-tls


resources:
  requests:
    cpu: "500m"
    memory: "1024Mi"
  limits:
    cpu: "1"
    memory: "1024Mi"