---
replicas: 1
minimumMasterNodes: 1
nodeGroup: "master"

roles:
  master: "true"
  ingest: "true"
  data: "true"

protocol: http

extraInitContainers:
  - name: volume-mount-hack
    image: busybox
    securityContext:
      runAsUser: 0
      privileged: true
    command: ["sh", "-c", "chown -R 1000:1000 /data && chmod 755 /data"]
    volumeMounts:
    - name: elasticsearch-master
      mountPath: /data

# Disable privileged init Container creation.
sysctlInitContainer:
  enabled: false

# Restrict the use of the memory-mapping when sysctlInitContainer is disabled.
esConfig:
  elasticsearch.yml: |
    node.store.allow_mmap: false
# Permit co-located instances for solitary minikube virtual machines.
antiAffinity: "soft"

# Shrink default JVM heap.
#esJavaOpts: "-Xmx256m -Xms256m"

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "1000m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

podSecurityContext:
  fsGroup: 1000
securityContext:
  runAsGroup: 1000
  runAsUser: 1000
