persistence:
  enabled: true

logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false
logstashPipeline:
  logstash.conf: |
    input { 
      beats {
        port => 5044
      }
    }
    output { 
      elasticsearch { 
        hosts => ["http://elasticsearch-master:9200"]
        index => "filebeats"
      }
    }

service:
  type: ClusterIP
  ports:
  - name: beats
    port: 5044
    protocol: TCP
    targetPort: 5044

